services:
  jobmanager:
    image: flink-with-ssh
    container_name: jobmanager
    hostname: jobmanager
    ports:
      - "8081:8081"  # Flink Web UI
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    command: jobmanager
    networks:
      - flink-network

  taskmanager1:
    image: flink-with-ssh
    container_name: taskmanager1
    hostname: taskmanager1
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    command: taskmanager
    networks:
      - flink-network

  taskmanager2:
    image: flink-with-ssh
    container_name: taskmanager2
    hostname: taskmanager2
    environment:
      - JOB_MANAGER_RPC_ADDRESS=jobmanager
    command: taskmanager
    networks:
      - flink-network

networks:
  flink-network:
    driver: bridge